In [2]:
import pandas as pd
import numpy as np
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
import xgboost as xgb
from sklearn.linear_model import LogisticRegression

In [3]:
df=pd.read_csv("E:\df_v4.csv")
df=df.drop(["Unnamed: 0"],axis=1)
df

0    1    2    3    4         5    6        7    8    9  ...  6391  \
0     0.0  0.0  0.0  0.0  0.0  0.000000  0.0  0.74902  1.0  1.0  ...   0.0   
1     1.0  1.0  1.0  1.0  1.0  1.000000  1.0  1.00000  1.0  1.0  ...   0.0   
2     1.0  1.0  1.0  1.0  1.0  1.000000  1.0  1.00000  1.0  1.0  ...   1.0   
3     1.0  1.0  1.0  1.0  1.0  1.000000  1.0  1.00000  1.0  1.0  ...   1.0   
4     1.0  1.0  1.0  1.0  1.0  1.000000  1.0  1.00000  1.0  1.0  ...   1.0   
...   ...  ...  ...  ...  ...       ...  ...      ...  ...  ...  ...   ...   
8933  1.0  1.0  1.0  1.0  1.0  1.000000  1.0  1.00000  1.0  1.0  ...   0.0   
8934  0.0  0.0  0.0  0.0  0.0  0.000000  0.0  0.00000  0.0  0.0  ...   1.0   
8935  1.0  1.0  1.0  1.0  1.0  1.000000  1.0  1.00000  1.0  1.0  ...   0.0   
8936  1.0  1.0  1.0  1.0  1.0  1.000000  1.0  1.00000  1.0  1.0  ...   0.0   
8937  0.0  0.0  0.0  0.0  0.0  0.235294  1.0  1.00000  1.0  1.0  ...   1.0   

      6392     6393  6394  6395  6396  6397  6398  6399  target  
0      0.0  0.00000   0.0   0.0   0.0   0.0   0.0   0.0       0  
1      0.0  0.00000   0.0   0.0   0.0   0.0   0.0   0.0       1  
2      1.0  1.00000   1.0   0.0   0.0   0.0   0.0   0.0       4  
3      1.0  1.00000   1.0   1.0   1.0   1.0   1.0   1.0       6  
4      1.0  1.00000   1.0   1.0   1.0   1.0   1.0   1.0       6  
...    ...      ...   ...   ...   ...   ...   ...   ...     ...  
8933   0.0  0.00000   0.0   0.0   0.0   0.0   0.0   0.0       1  
8934   1.0  0.25098   0.0   0.0   0.0   0.0   0.0   0.0       2  
8935   0.0  0.00000   0.0   0.0   0.0   0.0   0.0   0.0       1  
8936   0.0  0.00000   0.0   0.0   0.0   0.0   0.0   0.0       1  
8937   1.0  1.00000   1.0   1.0   0.0   0.0   0.0   0.0       2  

[8938 rows x 6401 columns]

In [3]:
df_x=df.iloc[:,:6400]
df_y=df["target"]
df_x

0    1    2    3    4         5    6    7    8    9  ...  6390  6391  \
0     0.0  0.0  0.0  0.0  0.0  0.000000  1.0  1.0  1.0  1.0  ...   1.0   1.0   
1     1.0  1.0  1.0  1.0  1.0  1.000000  1.0  1.0  1.0  1.0  ...   1.0   1.0   
2     1.0  1.0  1.0  1.0  1.0  1.000000  1.0  1.0  1.0  1.0  ...   1.0   1.0   
3     0.0  0.0  0.0  0.0  1.0  1.000000  1.0  1.0  1.0  1.0  ...   0.0   0.0   
4     0.0  0.0  0.0  0.0  1.0  1.000000  1.0  1.0  1.0  1.0  ...   0.0   0.0   
...   ...  ...  ...  ...  ...       ...  ...  ...  ...  ...  ...   ...   ...   
9585  0.0  0.0  0.0  0.0  0.0  0.000000  0.0  0.0  0.0  0.0  ...   0.0   0.0   
9586  1.0  1.0  1.0  1.0  1.0  1.000000  1.0  1.0  1.0  1.0  ...   1.0   1.0   
9587  0.0  0.0  0.0  0.0  0.0  0.000000  0.0  0.0  0.0  0.0  ...   1.0   1.0   
9588  1.0  1.0  1.0  1.0  1.0  1.000000  1.0  1.0  1.0  1.0  ...   1.0   1.0   
9589  0.0  0.0  0.0  0.0  0.0  0.313725  1.0  1.0  1.0  1.0  ...   1.0   1.0   

      6392  6393  6394  6395  6396  6397     6398  6399  
0      1.0   1.0   1.0   0.0   0.0   0.0  0.00000   0.0  
1      1.0   1.0   1.0   1.0   1.0   1.0  0.74902   1.0  
2      1.0   1.0   1.0   1.0   1.0   1.0  1.00000   1.0  
3      0.0   0.0   0.0   0.0   0.0   0.0  0.00000   0.0  
4      0.0   0.0   0.0   0.0   0.0   0.0  0.00000   0.0  
...    ...   ...   ...   ...   ...   ...      ...   ...  
9585   0.0   0.0   0.0   0.0   0.0   0.0  0.00000   0.0  
9586   1.0   1.0   1.0   1.0   1.0   1.0  0.74902   1.0  
9587   1.0   1.0   1.0   1.0   1.0   1.0  0.00000   0.0  
9588   1.0   1.0   1.0   1.0   1.0   1.0  0.74902   1.0  
9589   1.0   1.0   1.0   0.0   0.0   0.0  0.00000   0.0  

[9590 rows x 6400 columns]

In [4]:
x_train,x_test,y_train,y_test=train_test_split(df_x,df_y,test_size=0.3)

In [5]:
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(6713, 6400)
(6713,)
(2877, 6400)
(2877,)


In [6]:
model=SVC()

In [7]:
%%time
model.fit(x_train,y_train)

Wall time: 5.11 s


SVC()

In [8]:
%%time
pred=model.predict(x_test)

Wall time: 1.5 s


In [9]:
accuracy_score(pred,y_test)*100

100.0

In [10]:
print(classification_report(pred,y_test))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       416
           1       1.00      1.00      1.00       912
           2       1.00      1.00      1.00       304
           3       1.00      1.00      1.00       283
           4       1.00      1.00      1.00       345
           5       1.00      1.00      1.00       302
           6       1.00      1.00      1.00       315

    accuracy                           1.00      2877
   macro avg       1.00      1.00      1.00      2877
weighted avg       1.00      1.00      1.00      2877



In [11]:
confusion_matrix(pred,y_test)

array([[416,   0,   0,   0,   0,   0,   0],
       [  0, 912,   0,   0,   0,   0,   0],
       [  0,   0, 304,   0,   0,   0,   0],
       [  0,   0,   0, 283,   0,   0,   0],
       [  0,   0,   0,   0, 345,   0,   0],
       [  0,   0,   0,   0,   0, 302,   0],
       [  0,   0,   0,   0,   0,   0, 315]], dtype=int64)

In [12]:
df_test=pd.read_csv("test_data_v2.csv")
df_test=df_test.drop(["Unnamed: 0"],axis=1)
df_test

0    1    2    3    4        5         6    7    8         9  ...  \
0    1.0  1.0  1.0  1.0  1.0  1.00000  1.000000  1.0  1.0  1.000000  ...   
1    0.0  0.0  0.0  0.0  0.0  0.00000  0.000000  0.0  0.0  0.000000  ...   
2    1.0  1.0  1.0  1.0  1.0  1.00000  1.000000  1.0  1.0  1.000000  ...   
3    1.0  1.0  1.0  1.0  1.0  1.00000  1.000000  1.0  1.0  1.000000  ...   
4    1.0  1.0  1.0  1.0  1.0  0.74902  0.298039  1.0  1.0  1.000000  ...   
..   ...  ...  ...  ...  ...      ...       ...  ...  ...       ...  ...   
995  0.0  0.0  0.0  0.0  0.0  0.00000  0.000000  0.0  0.0  0.000000  ...   
996  0.0  0.0  0.0  0.0  0.0  0.00000  0.000000  0.0  0.0  0.000000  ...   
997  0.0  0.0  0.0  0.0  0.0  0.00000  0.000000  0.0  0.0  0.000000  ...   
998  0.0  0.0  0.0  0.0  0.0  0.00000  0.000000  0.0  0.0  0.235294  ...   
999  0.0  0.0  0.0  0.0  0.0  1.00000  1.000000  1.0  1.0  1.000000  ...   

     6391  6392  6393      6394  6395  6396  6397  6398  6399  target  
0     1.0   1.0   1.0  1.000000   1.0   1.0   1.0   1.0   1.0       6  
1     0.0   0.0   0.0  0.000000   0.0   0.0   0.0   0.0   0.0       4  
2     1.0   1.0   1.0  1.000000   1.0   1.0   1.0   1.0   1.0       1  
3     1.0   1.0   1.0  1.000000   1.0   1.0   1.0   1.0   1.0       1  
4     1.0   1.0   1.0  1.000000   1.0   1.0   1.0   1.0   1.0       1  
..    ...   ...   ...       ...   ...   ...   ...   ...   ...     ...  
995   0.0   0.0   0.0  0.000000   0.0   0.0   0.0   0.0   0.0       4  
996   0.0   0.0   0.0  0.000000   0.0   0.0   0.0   0.0   0.0       4  
997   0.0   0.0   0.0  0.000000   0.0   0.0   0.0   0.0   0.0       4  
998   0.0   0.0   0.0  0.000000   0.0   0.0   0.0   0.0   0.0       0  
999   1.0   1.0   1.0  0.313725   0.0   0.0   0.0   0.0   0.0       0  

[1000 rows x 6401 columns]

In [13]:
x_test_crea=df_test.drop(["target"],axis=1)
y_test_crea=df_test["target"]

In [14]:
pred=model.predict(x_test_crea)

In [15]:
accuracy_score(pred,y_test_crea)*100

69.8

In [16]:
print(classification_report(pred,y_test_crea))

              precision    recall  f1-score   support

           0       1.00      0.30      0.46       429
           1       0.00      0.00      0.00         0
           2       1.00      1.00      1.00        89
           3       1.00      1.00      1.00       116
           4       1.00      1.00      1.00       149
           5       1.00      1.00      1.00       114
           6       1.00      1.00      1.00       103

    accuracy                           0.70      1000
   macro avg       0.86      0.76      0.78      1000
weighted avg       1.00      0.70      0.77      1000



C:\Users\chait\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\chait\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\chait\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [17]:
confusion_matrix(pred,y_test_crea)

array([[127, 302,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0],
       [  0,   0,  89,   0,   0,   0,   0],
       [  0,   0,   0, 116,   0,   0,   0],
       [  0,   0,   0,   0, 149,   0,   0],
       [  0,   0,   0,   0,   0, 114,   0],
       [  0,   0,   0,   0,   0,   0, 103]], dtype=int64)

In [18]:
 model = xgb.XGBClassifier()

In [ ]:
 model = xgb.XGBClassifier()

In [19]:
%%time
model.fit(x_train,y_train)

Wall time: 45.9 s


XGBClassifier(base_score=0.5, booster='gbtree', callbacks=None,
              colsample_bylevel=1, colsample_bynode=1, colsample_bytree=1,
              early_stopping_rounds=None, enable_categorical=False,
              eval_metric=None, feature_types=None, gamma=0, gpu_id=-1,
              grow_policy='depthwise', importance_type=None,
              interaction_constraints='', learning_rate=0.300000012,
              max_bin=256, max_cat_threshold=64, max_cat_to_onehot=4,
              max_delta_step=0, max_depth=6, max_leaves=0, min_child_weight=1,
              missing=nan, monotone_constraints='()', n_estimators=100,
              n_jobs=0, num_parallel_tree=1, objective='multi:softprob',
              predictor='auto', ...)

In [20]:
%%time
pred=model.predict(x_test)

Wall time: 306 ms


In [21]:
accuracy_score(pred,y_test)*100

100.0

In [22]:
print(classification_report(pred,y_test))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       416
           1       1.00      1.00      1.00       912
           2       1.00      1.00      1.00       304
           3       1.00      1.00      1.00       283
           4       1.00      1.00      1.00       345
           5       1.00      1.00      1.00       302
           6       1.00      1.00      1.00       315

    accuracy                           1.00      2877
   macro avg       1.00      1.00      1.00      2877
weighted avg       1.00      1.00      1.00      2877



In [23]:
confusion_matrix(pred,y_test)

array([[416,   0,   0,   0,   0,   0,   0],
       [  0, 912,   0,   0,   0,   0,   0],
       [  0,   0, 304,   0,   0,   0,   0],
       [  0,   0,   0, 283,   0,   0,   0],
       [  0,   0,   0,   0, 345,   0,   0],
       [  0,   0,   0,   0,   0, 302,   0],
       [  0,   0,   0,   0,   0,   0, 315]], dtype=int64)

In [24]:
pred=model.predict(x_test_crea)

In [25]:
accuracy_score(pred,y_test_crea)*100

69.8

In [26]:
print(classification_report(pred,y_test_crea))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       127
           1       0.00      0.00      0.00         0
           2       1.00      1.00      1.00        89
           3       1.00      1.00      1.00       116
           4       1.00      1.00      1.00       149
           5       1.00      0.71      0.83       161
           6       1.00      0.29      0.45       358

    accuracy                           0.70      1000
   macro avg       0.86      0.71      0.75      1000
weighted avg       1.00      0.70      0.77      1000



C:\Users\chait\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\chait\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\chait\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [27]:
confusion_matrix(pred,y_test_crea)

array([[127,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0],
       [  0,   0,  89,   0,   0,   0,   0],
       [  0,   0,   0, 116,   0,   0,   0],
       [  0,   0,   0,   0, 149,   0,   0],
       [  0,  47,   0,   0,   0, 114,   0],
       [  0, 255,   0,   0,   0,   0, 103]], dtype=int64)

In [28]:
 model = LogisticRegression()

In [29]:
%%time
model.fit(x_train,y_train)

Wall time: 8.71 s


C:\Users\chait\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [30]:
%%time
pred=model.predict(x_test)

Wall time: 78.4 ms


In [31]:
accuracy_score(pred,y_test)*100

100.0

In [32]:
print(classification_report(pred,y_test))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       416
           1       1.00      1.00      1.00       912
           2       1.00      1.00      1.00       304
           3       1.00      1.00      1.00       283
           4       1.00      1.00      1.00       345
           5       1.00      1.00      1.00       302
           6       1.00      1.00      1.00       315

    accuracy                           1.00      2877
   macro avg       1.00      1.00      1.00      2877
weighted avg       1.00      1.00      1.00      2877



In [33]:
confusion_matrix(pred,y_test)

array([[416,   0,   0,   0,   0,   0,   0],
       [  0, 912,   0,   0,   0,   0,   0],
       [  0,   0, 304,   0,   0,   0,   0],
       [  0,   0,   0, 283,   0,   0,   0],
       [  0,   0,   0,   0, 345,   0,   0],
       [  0,   0,   0,   0,   0, 302,   0],
       [  0,   0,   0,   0,   0,   0, 315]], dtype=int64)

In [34]:
pred=model.predict(x_test_crea)

In [35]:
accuracy_score(pred,y_test_crea)*100

71.89999999999999

In [36]:
print(classification_report(pred,y_test_crea))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       127
           1       0.07      1.00      0.13        21
           2       1.00      1.00      1.00        89
           3       1.00      1.00      1.00       116
           4       1.00      1.00      1.00       149
           5       1.00      1.00      1.00       114
           6       1.00      0.27      0.42       384

    accuracy                           0.72      1000
   macro avg       0.87      0.90      0.79      1000
weighted avg       0.98      0.72      0.76      1000



In [37]:
confusion_matrix(pred,y_test_crea)

array([[127,   0,   0,   0,   0,   0,   0],
       [  0,  21,   0,   0,   0,   0,   0],
       [  0,   0,  89,   0,   0,   0,   0],
       [  0,   0,   0, 116,   0,   0,   0],
       [  0,   0,   0,   0, 149,   0,   0],
       [  0,   0,   0,   0,   0, 114,   0],
       [  0, 281,   0,   0,   0,   0, 103]], dtype=int64)

In [38]:
pd.Series(y_test_crea).value_counts()

1    302
4    149
0    127
3    116
5    114
6    103
2     89
Name: target, dtype: int64