In [1]:
import cv2
import numpy as np
import pandas as pd
import random
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv("E:\df_v4.csv",index_col=False)
df=df.drop(["Unnamed: 0"],axis=1)
df

0    1    2    3    4         5    6    7    8    9  ...  6391  6392  \
0     0.0  0.0  0.0  0.0  0.0  0.000000  1.0  1.0  1.0  1.0  ...   1.0   1.0   
1     1.0  1.0  1.0  1.0  1.0  1.000000  1.0  1.0  1.0  1.0  ...   1.0   1.0   
2     1.0  1.0  1.0  1.0  1.0  1.000000  1.0  1.0  1.0  1.0  ...   1.0   1.0   
3     0.0  0.0  0.0  0.0  1.0  1.000000  1.0  1.0  1.0  1.0  ...   0.0   0.0   
4     0.0  0.0  0.0  0.0  1.0  1.000000  1.0  1.0  1.0  1.0  ...   0.0   0.0   
...   ...  ...  ...  ...  ...       ...  ...  ...  ...  ...  ...   ...   ...   
9585  0.0  0.0  0.0  0.0  0.0  0.000000  0.0  0.0  0.0  0.0  ...   0.0   0.0   
9586  1.0  1.0  1.0  1.0  1.0  1.000000  1.0  1.0  1.0  1.0  ...   1.0   1.0   
9587  0.0  0.0  0.0  0.0  0.0  0.000000  0.0  0.0  0.0  0.0  ...   1.0   1.0   
9588  1.0  1.0  1.0  1.0  1.0  1.000000  1.0  1.0  1.0  1.0  ...   1.0   1.0   
9589  0.0  0.0  0.0  0.0  0.0  0.313725  1.0  1.0  1.0  1.0  ...   1.0   1.0   

      6393  6394  6395  6396  6397     6398  6399  target  
0      1.0   1.0   0.0   0.0   0.0  0.00000   0.0       0  
1      1.0   1.0   1.0   1.0   1.0  0.74902   1.0       1  
2      1.0   1.0   1.0   1.0   1.0  1.00000   1.0       6  
3      0.0   0.0   0.0   0.0   0.0  0.00000   0.0       2  
4      0.0   0.0   0.0   0.0   0.0  0.00000   0.0       2  
...    ...   ...   ...   ...   ...      ...   ...     ...  
9585   0.0   0.0   0.0   0.0   0.0  0.00000   0.0       4  
9586   1.0   1.0   1.0   1.0   1.0  0.74902   1.0       1  
9587   1.0   1.0   1.0   1.0   1.0  0.00000   0.0       3  
9588   1.0   1.0   1.0   1.0   1.0  0.74902   1.0       1  
9589   1.0   1.0   0.0   0.0   0.0  0.00000   0.0       0  

[9590 rows x 6401 columns]

In [3]:
def augment(img):
    img1 = cv2.rotate(img, cv2.ROTATE_90_CLOCKWISE)
    img2 = cv2.rotate(img, cv2.ROTATE_90_COUNTERCLOCKWISE)
    img3 = cv2.rotate(img, cv2.ROTATE_180)
    a=[img1,img2,img3]
    img_ran1=random.sample(a,1) 
    img_ran1=np.array(img_ran1).reshape(80,80)
   # plt.imshow(img_ran1)
    img4 = cv2.flip(img_ran1, 0)
    img5 = cv2.flip(img_ran1, 1)
    a=[img4,img5]
    img_ran2=random.sample(a,1)
    img_ran2=np.array(img_ran2).reshape(80,80)
    a=[img_ran1,img_ran2]
    
    return random.sample(a,1)

In [4]:
df_x=df.drop(["target"],axis=1)
df_y=np.array(df["target"])
arr=[]
d={}
num=[]
for i in range(9590):
    num.append(i)
    temp=df_x.iloc[i,:]
    arr.append(np.array(temp).reshape(80,80))
    d[i]=df_y[i]

In [5]:
d

{0: 0,
 1: 1,
 2: 6,
 3: 2,
 4: 2,
 5: 1,
 6: 1,
 7: 4,
 8: 6,
 9: 0,
 10: 0,
 11: 1,
 12: 3,
 13: 2,
 14: 1,
 15: 1,
 16: 2,
 17: 0,
 18: 3,
 19: 3,
 20: 1,
 21: 1,
 22: 1,
 23: 3,
 24: 1,
 25: 1,
 26: 1,
 27: 4,
 28: 3,
 29: 6,
 30: 6,
 31: 0,
 32: 6,
 33: 5,
 34: 1,
 35: 1,
 36: 4,
 37: 3,
 38: 2,
 39: 6,
 40: 4,
 41: 6,
 42: 1,
 43: 4,
 44: 1,
 45: 3,
 46: 5,
 47: 6,
 48: 3,
 49: 2,
 50: 1,
 51: 1,
 52: 4,
 53: 1,
 54: 1,
 55: 3,
 56: 0,
 57: 5,
 58: 4,
 59: 2,
 60: 1,
 61: 1,
 62: 1,
 63: 1,
 64: 5,
 65: 1,
 66: 2,
 67: 0,
 68: 0,
 69: 1,
 70: 6,
 71: 1,
 72: 1,
 73: 3,
 74: 2,
 75: 1,
 76: 6,
 77: 1,
 78: 6,
 79: 0,
 80: 4,
 81: 4,
 82: 1,
 83: 0,
 84: 0,
 85: 4,
 86: 2,
 87: 3,
 88: 1,
 89: 1,
 90: 5,
 91: 1,
 92: 4,
 93: 0,
 94: 1,
 95: 1,
 96: 6,
 97: 1,
 98: 5,
 99: 6,
 100: 1,
 101: 0,
 102: 5,
 103: 5,
 104: 4,
 105: 1,
 106: 4,
 107: 1,
 108: 5,
 109: 0,
 110: 1,
 111: 1,
 112: 1,
 113: 4,
 114: 4,
 115: 1,
 116: 1,
 117: 3,
 118: 0,
 119: 4,
 120: 4,
 121: 3,
 122: 0,
 12

In [6]:
test_x_augmented=[]
test_y_augmented=[]
for i in range(1000):
    n=1
    index=random.sample(num,n)
    
    test_x_augmented.append(augment(arr[int(index[0])]))
    test_y_augmented.append(d[int(index[0])])
    
print(test_x_augmented)  

[[array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.]])], [array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])], [array([[1.        , 1.        , 1.        , ..., 1.        , 1.        ,
        1.        ],
       [1.        , 1.        , 1.        , ..., 1.        , 1.        ,
        1.        ],
       [1.        , 1.        , 1.        , ..., 1.        , 1.        ,
        1.        ],
       ...,
       [1.        , 1.        , 1.        , ..., 1.        , 1.        ,
        1.        ],
       [1.        , 1.        , 1.        , ..., 1.        , 1.        ,
        1.        ],
       [1.        , 0.749019

In [7]:
pd.Series(test_y_augmented).value_counts()

1    302
4    149
0    127
3    116
5    114
6    103
2     89
dtype: int64

In [8]:
data_flat=[]
for i in range(len(test_x_augmented)):
    temp=np.array(test_x_augmented[i]).flatten()
    data_flat.append(np.array(temp))
data_flat

[array([1., 1., 1., ..., 1., 1., 1.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([1., 1., 1., ..., 1., 1., 1.]),
 array([1., 1., 1., ..., 1., 1., 1.]),
 array([1., 1., 1., ..., 1., 1., 1.]),
 array([1., 1., 1., ..., 1., 1., 1.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([1., 1., 1., ..., 1., 1., 1.]),
 array([0., 0., 1., ..., 0., 0., 0.]),
 array([1., 1., 1., ..., 1., 1., 1.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 1., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([1., 0., 1., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 1., 0., 1.]),
 array([1., 1., 1., ..., 1., 1., 1.]),
 array([0., 0., 0., ..., 1., 0., 1.]),
 array([1.        , 0.74901961, 1.        , ..., 1.        , 1.        ,
        1.        ]),
 array([1.        , 0.        , 0.68627451, ..., 1.        , 1.        ,
        0.        ]),
 array([1., 1., 1., ..., 1., 1., 1.]),
 array([1., 1., 1., ..., 1., 1

In [9]:
df=pd.DataFrame(data_flat)
df

0     1     2     3     4        5         6     7     8         9     \
0     1.0   1.0   1.0   1.0   1.0  1.00000  1.000000   1.0   1.0  1.000000   
1     0.0   0.0   0.0   0.0   0.0  0.00000  0.000000   0.0   0.0  0.000000   
2     1.0   1.0   1.0   1.0   1.0  1.00000  1.000000   1.0   1.0  1.000000   
3     1.0   1.0   1.0   1.0   1.0  1.00000  1.000000   1.0   1.0  1.000000   
4     1.0   1.0   1.0   1.0   1.0  0.74902  0.298039   1.0   1.0  1.000000   
..    ...   ...   ...   ...   ...      ...       ...   ...   ...       ...   
995   0.0   0.0   0.0   0.0   0.0  0.00000  0.000000   0.0   0.0  0.000000   
996   0.0   0.0   0.0   0.0   0.0  0.00000  0.000000   0.0   0.0  0.000000   
997   0.0   0.0   0.0   0.0   0.0  0.00000  0.000000   0.0   0.0  0.000000   
998   0.0   0.0   0.0   0.0   0.0  0.00000  0.000000   0.0   0.0  0.235294   
999   0.0   0.0   0.0   0.0   0.0  1.00000  1.000000   1.0   1.0  1.000000   

     ...  6390  6391  6392  6393      6394  6395  6396  6397  6398  6399  
0    ...   1.0   1.0   1.0   1.0  1.000000   1.0   1.0   1.0   1.0   1.0  
1    ...   0.0   0.0   0.0   0.0  0.000000   0.0   0.0   0.0   0.0   0.0  
2    ...   1.0   1.0   1.0   1.0  1.000000   1.0   1.0   1.0   1.0   1.0  
3    ...   1.0   1.0   1.0   1.0  1.000000   1.0   1.0   1.0   1.0   1.0  
4    ...   1.0   1.0   1.0   1.0  1.000000   1.0   1.0   1.0   1.0   1.0  
..   ...   ...   ...   ...   ...       ...   ...   ...   ...   ...   ...  
995  ...   0.0   0.0   0.0   0.0  0.000000   0.0   0.0   0.0   0.0   0.0  
996  ...   0.0   0.0   0.0   0.0  0.000000   0.0   0.0   0.0   0.0   0.0  
997  ...   0.0   0.0   0.0   0.0  0.000000   0.0   0.0   0.0   0.0   0.0  
998  ...   0.0   0.0   0.0   0.0  0.000000   0.0   0.0   0.0   0.0   0.0  
999  ...   1.0   1.0   1.0   1.0  0.313725   0.0   0.0   0.0   0.0   0.0  

[1000 rows x 6400 columns]

In [10]:
df["target"]=test_y_augmented
df

0    1    2    3    4        5         6    7    8         9  ...  \
0    1.0  1.0  1.0  1.0  1.0  1.00000  1.000000  1.0  1.0  1.000000  ...   
1    0.0  0.0  0.0  0.0  0.0  0.00000  0.000000  0.0  0.0  0.000000  ...   
2    1.0  1.0  1.0  1.0  1.0  1.00000  1.000000  1.0  1.0  1.000000  ...   
3    1.0  1.0  1.0  1.0  1.0  1.00000  1.000000  1.0  1.0  1.000000  ...   
4    1.0  1.0  1.0  1.0  1.0  0.74902  0.298039  1.0  1.0  1.000000  ...   
..   ...  ...  ...  ...  ...      ...       ...  ...  ...       ...  ...   
995  0.0  0.0  0.0  0.0  0.0  0.00000  0.000000  0.0  0.0  0.000000  ...   
996  0.0  0.0  0.0  0.0  0.0  0.00000  0.000000  0.0  0.0  0.000000  ...   
997  0.0  0.0  0.0  0.0  0.0  0.00000  0.000000  0.0  0.0  0.000000  ...   
998  0.0  0.0  0.0  0.0  0.0  0.00000  0.000000  0.0  0.0  0.235294  ...   
999  0.0  0.0  0.0  0.0  0.0  1.00000  1.000000  1.0  1.0  1.000000  ...   

     6391  6392  6393      6394  6395  6396  6397  6398  6399  target  
0     1.0   1.0   1.0  1.000000   1.0   1.0   1.0   1.0   1.0       6  
1     0.0   0.0   0.0  0.000000   0.0   0.0   0.0   0.0   0.0       4  
2     1.0   1.0   1.0  1.000000   1.0   1.0   1.0   1.0   1.0       1  
3     1.0   1.0   1.0  1.000000   1.0   1.0   1.0   1.0   1.0       1  
4     1.0   1.0   1.0  1.000000   1.0   1.0   1.0   1.0   1.0       1  
..    ...   ...   ...       ...   ...   ...   ...   ...   ...     ...  
995   0.0   0.0   0.0  0.000000   0.0   0.0   0.0   0.0   0.0       4  
996   0.0   0.0   0.0  0.000000   0.0   0.0   0.0   0.0   0.0       4  
997   0.0   0.0   0.0  0.000000   0.0   0.0   0.0   0.0   0.0       4  
998   0.0   0.0   0.0  0.000000   0.0   0.0   0.0   0.0   0.0       0  
999   1.0   1.0   1.0  0.313725   0.0   0.0   0.0   0.0   0.0       0  

[1000 rows x 6401 columns]

In [11]:
df.to_csv("test_data_v2.csv")